# Generated by Django 5.2.10 on 2026-02-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('category', models.CharField(choices=[('coloring', 'Окрашивание'), ('manicure', 'Маникюр'), ('massage', 'Массаж'), ('cosmetology', 'Косметология')], max_length=50, verbose_name='Категория')),
                ('duration', models.IntegerField(verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('master', 'Мастер'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50, verbose_name='Специализация')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('description', models.TextField(verbose_name='О мастере')),
                ('photo', models.ImageField(null=True, upload_to='images/', verbose_name='Фотография мастера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to='myapp.users', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждение'), ('confirmed', 'Подтверждено'), ('complated', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.masters', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.services', verbose_name='Услуга')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.users', verbose_name='Клиент')),
            ],
        ),
    ]
