# Generated by Django 6.0.1 on 2026-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
    ]
