# Generated by Django 6.0.1 on 2026-02-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фотография мастера'),
        ),
    ]
