# Generated by Django 6.0.1 on 2026-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_masters_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]